#!/bin/sh 
mount -t proc proc /proc

cat /proc/cmdline | grep "switch.rootfs" >/dev/null
data=$?
if [ $data -eq 0 ];then
	echo "need to switch sysroot, direct exec /etc/init.d/rcS"
	cmd="/etc/init.d/rcS"
else
	echo "not need to switch sysroot, exec /linuxrc"
	cmd="/linuxrc"
fi
exec $cmd


